// SPDX-License-Identifier: GPL-2.0-or-later
/*
 *  Hop-by-Hop Path Tracing implementation
 *
 *  Author:
 *  Andrea Mayer <andrea.mayer@uniroma2.it>
 */

#ifndef _UAPI_LINUX_IPV6_HOPPT_H
#define _UAPI_LINUX_IPV6_HOPPT_H

#define IPV6_HOPPT_GENL_NAME		"IPV6_HOPPT"
#define IPV6_HOPPT_GENL_VERSION		0x1

enum {
	IPV6_HOPPT_TTS_TMPL_UNSPEC	= 0,
	IPV6_HOPPT_TTS_TMPL_1,
	IPV6_HOPPT_TTS_TMPL_2,
	IPV6_HOPPT_TTS_TMPL_3,
	IPV6_HOPPT_TTS_TMPL_4,
	__IPV6_HOPPT_TTS_TMPL_MAX,
};
#define IPV6_HOPPT_TTS_TMPL_MAX (__IPV6_HOPPT_TTS_TMPL_MAX - 1)

enum {
	IPV6_HOPPT_ATTR_UNSPEC		= 0,
	IPV6_HOPPT_ATTR_ID,
	IPV6_HOPPT_ATTR_IFINDEX,
	IPV6_HOPPT_ATTR_TTSTMPL,
	__IPV6_HOPPT_ATTR_MAX,
};
#define IPV6_HOPPT_ATTR_MAX (__IPV6_HOPPT_ATTR_MAX - 1)

enum {
	IPV6_HOPPT_CMD_UNSPEC		= 0,
	IPV6_HOPPT_CMD_ADD_ID,
	IPV6_HOPPT_CMD_DEL_ID,
	IPV6_HOPPT_CMD_SHOW_ID,
	IPV6_HOPPT_CMD_DUMP_ID,
	IPV6_HOPPT_CMD_TGRCV_ADD_ID,
	IPV6_HOPPT_CMD_TGRCV_DEL_ID,
	IPV6_HOPPT_CMD_TGRCV_DUMP_ID,
	__IPV6_HOPPT_CMD_MAX,
};
#define IPV6_HOPPT_CMD_MAX (__IPV6_HOPPT_CMD_MAX - 1)

#endif
